#define HKEY_BITS (128)

#define BUCKET_BITS (8)
#define LSLOT_BITS (8)
#define FINGERPRINT_BITS (HKEY_BITS - BUCKET_BITS - LSLOT_BITS)

#define NUM_BUCKETS (1 << BUCKET_BITS)
#define NUM_LSLOTS (1 << LSLOT_BITS)
#define NUM_ENTRIES_PER_LSLOT (1 << FINGERPRINT_BITS)

#define ALLOTTED_BITS_PER_ENTRY (4)
#define MAX_LSLOT_SIZE (NUM_ENTRIES_PER_LSLOT * ALLOTTED_BITS_PER_ENTRY)
#define MAX_BUCKET_SIZE (MAX_LSLOT_SIZE * NUM_LSLOTS)
